- name: Add test user to docker group (Ansible >= 2.5.0)
  user:
    name: "{{ test_user }}"
    groups: docker
    append: yes
    create_home: yes
  when: ansible_version.full is version_compare('2.5.0', '>=')

- name: Add test user to docker group (Ansible < 2.5.0)
  user:
    name: "{{ test_user }}"
    groups: docker
    append: yes
    createhome: yes
  when: ansible_version.full is version_compare('2.5.0', '<')

- name: Create Docker daemon configuration from template
  template:
    src: templates/docker.json.j2
    dest: /etc/docker/daemon.json
  register: docker_config

- name: Restart Docker
  service:
    name: docker
    daemon_reload: yes
    state: restarted
  when: docker_config.changed
